sudo: false

language: node_js
node_js:
  - 8

cache:
  directories:
    - ~/.npm
notifications:
  email: false

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build

branches:
  only:
    - master

jobs:
  include:
    - stage: npm release
      if: branch = master
      node_js: "8"
      script: npm run semantic-release