sudo: false

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - ~/.npm

notifications:
  email: false

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm test
    - stage: compile
      script: npm run build -- --copy-files
    - stage: npm release
      if: branch = master
      node_js: "stable"
      script: npm run semantic-release