sudo: false

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - ~/.npm

notifications:
  email: false

script:
  - npm test
  - npm run build

jobs:
  include:
    - stage: npm release
      if: branch = master
      node_js: "8"
      script: npm run semantic-release